# уменьшить задержку после префикса
set-option -s escape-time 0

# оставить Ctrl-b и добавить Ctrl-a
set-option -g prefix2 C-a
bind C-a send-prefix

# включить мышь
set -g mouse on
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'
# vim-режим (ВАЖНО)
setw -g mode-keys vi
set-option -g status-position top	
# цвет выделения (оранжевый)
# set -g mode-style bg=#FDAA48,fg=#FFFFFF
#set -g message-style bg=#FDAA48,fg=#FFFFFF
#set -g message-command-style bg=#FDAA48,fg=#FFFFFF
